/**
 * New Testament Book Information
 * Includes canonical order, chapter counts, abbreviations, and metadata
 */

export const NT_BOOKS = [
  {
    id: 'matthew',
    name: 'Matthew',
    spanish: 'Mateo',
    abbreviation: 'Matt',
    order: 1,
    chapters: 28,
    testament: 'new',
    category: 'gospel',
    author: 'Matthew',
    writingDate: '70-90 CE',
  },
  {
    id: 'mark',
    name: 'Mark',
    spanish: 'Marcos',
    abbreviation: 'Mark',
    order: 2,
    chapters: 16,
    testament: 'new',
    category: 'gospel',
    author: 'Mark',
    writingDate: '65-70 CE',
  },
  {
    id: 'luke',
    name: 'Luke',
    spanish: 'Lucas',
    abbreviation: 'Luke',
    order: 3,
    chapters: 24,
    testament: 'new',
    category: 'gospel',
    author: 'Luke',
    writingDate: '75-90 CE',
  },
  {
    id: 'john',
    name: 'John',
    spanish: 'Juan',
    abbreviation: 'John',
    order: 4,
    chapters: 21,
    testament: 'new',
    category: 'gospel',
    author: 'John',
    writingDate: '90-110 CE',
  },
  {
    id: 'acts',
    name: 'Acts',
    spanish: 'Hechos',
    abbreviation: 'Acts',
    order: 5,
    chapters: 28,
    testament: 'new',
    category: 'history',
    author: 'Luke',
    writingDate: '75-90 CE',
  },
  {
    id: 'romans',
    name: 'Romans',
    spanish: 'Romanos',
    abbreviation: 'Rom',
    order: 6,
    chapters: 16,
    testament: 'new',
    category: 'epistle',
    author: 'Paul',
    writingDate: '54-58 CE',
  },
  {
    id: '1-corinthians',
    name: '1 Corinthians',
    spanish: '1 Corintios',
    abbreviation: '1 Cor',
    order: 7,
    chapters: 16,
    testament: 'new',
    category: 'epistle',
    author: 'Paul',
    writingDate: '53-54 CE',
  },
  {
    id: '2-corinthians',
    name: '2 Corinthians',
    spanish: '2 Corintios',
    abbreviation: '2 Cor',
    order: 8,
    chapters: 13,
    testament: 'new',
    category: 'epistle',
    author: 'Paul',
    writingDate: '55-56 CE',
  },
  {
    id: 'galatians',
    name: 'Galatians',
    spanish: 'Gálatas',
    abbreviation: 'Gal',
    order: 9,
    chapters: 6,
    testament: 'new',
    category: 'epistle',
    author: 'Paul',
    writingDate: '49-54 CE',
  },
  {
    id: 'ephesians',
    name: 'Ephesians',
    spanish: 'Efesios',
    abbreviation: 'Eph',
    order: 10,
    chapters: 6,
    testament: 'new',
    category: 'epistle',
    author: 'Paul',
    writingDate: '60-62 CE',
  },
  {
    id: 'philippians',
    name: 'Philippians',
    spanish: 'Filipenses',
    abbreviation: 'Phil',
    order: 11,
    chapters: 4,
    testament: 'new',
    category: 'epistle',
    author: 'Paul',
    writingDate: '60-62 CE',
  },
  {
    id: 'colossians',
    name: 'Colossians',
    spanish: 'Colosenses',
    abbreviation: 'Col',
    order: 12,
    chapters: 4,
    testament: 'new',
    category: 'epistle',
    author: 'Paul',
    writingDate: '60-62 CE',
  },
  {
    id: '1-thessalonians',
    name: '1 Thessalonians',
    spanish: '1 Tesalonicenses',
    abbreviation: '1 Thess',
    order: 13,
    chapters: 5,
    testament: 'new',
    category: 'epistle',
    author: 'Paul',
    writingDate: '50-51 CE',
  },
  {
    id: '2-thessalonians',
    name: '2 Thessalonians',
    spanish: '2 Tesalonicenses',
    abbreviation: '2 Thess',
    order: 14,
    chapters: 3,
    testament: 'new',
    category: 'epistle',
    author: 'Paul',
    writingDate: '51-52 CE',
  },
  {
    id: '1-timothy',
    name: '1 Timothy',
    spanish: '1 Timoteo',
    abbreviation: '1 Tim',
    order: 15,
    chapters: 6,
    testament: 'new',
    category: 'epistle',
    author: 'Paul',
    writingDate: '62-64 CE',
  },
  {
    id: '2-timothy',
    name: '2 Timothy',
    spanish: '2 Timoteo',
    abbreviation: '2 Tim',
    order: 16,
    chapters: 4,
    testament: 'new',
    category: 'epistle',
    author: 'Paul',
    writingDate: '64-67 CE',
  },
  {
    id: 'titus',
    name: 'Titus',
    spanish: 'Tito',
    abbreviation: 'Titus',
    order: 17,
    chapters: 3,
    testament: 'new',
    category: 'epistle',
    author: 'Paul',
    writingDate: '62-64 CE',
  },
  {
    id: 'philemon',
    name: 'Philemon',
    spanish: 'Filemón',
    abbreviation: 'Phlm',
    order: 18,
    chapters: 1,
    testament: 'new',
    category: 'epistle',
    author: 'Paul',
    writingDate: '60-62 CE',
  },
  {
    id: 'hebrews',
    name: 'Hebrews',
    spanish: 'Hebreos',
    abbreviation: 'Heb',
    order: 19,
    chapters: 13,
    testament: 'new',
    category: 'epistle',
    author: 'Unknown',
    writingDate: '60-80 CE',
  },
  {
    id: 'james',
    name: 'James',
    spanish: 'Santiago',
    abbreviation: 'Jas',
    order: 20,
    chapters: 5,
    testament: 'new',
    category: 'epistle',
    author: 'James',
    writingDate: '45-62 CE',
  },
  {
    id: '1-peter',
    name: '1 Peter',
    spanish: '1 Pedro',
    abbreviation: '1 Pet',
    order: 21,
    chapters: 5,
    testament: 'new',
    category: 'epistle',
    author: 'Peter',
    writingDate: '62-64 CE',
  },
  {
    id: '2-peter',
    name: '2 Peter',
    spanish: '2 Pedro',
    abbreviation: '2 Pet',
    order: 22,
    chapters: 3,
    testament: 'new',
    category: 'epistle',
    author: 'Peter',
    writingDate: '64-68 CE',
  },
  {
    id: '1-john',
    name: '1 John',
    spanish: '1 Juan',
    abbreviation: '1 John',
    order: 23,
    chapters: 5,
    testament: 'new',
    category: 'epistle',
    author: 'John',
    writingDate: '90-110 CE',
  },
  {
    id: '2-john',
    name: '2 John',
    spanish: '2 Juan',
    abbreviation: '2 John',
    order: 24,
    chapters: 1,
    testament: 'new',
    category: 'epistle',
    author: 'John',
    writingDate: '90-110 CE',
  },
  {
    id: '3-john',
    name: '3 John',
    spanish: '3 Juan',
    abbreviation: '3 John',
    order: 25,
    chapters: 1,
    testament: 'new',
    category: 'epistle',
    author: 'John',
    writingDate: '90-110 CE',
  },
  {
    id: 'jude',
    name: 'Jude',
    spanish: 'Judas',
    abbreviation: 'Jude',
    order: 26,
    chapters: 1,
    testament: 'new',
    category: 'epistle',
    author: 'Jude',
    writingDate: '65-80 CE',
  },
  {
    id: 'revelation',
    name: 'Revelation',
    spanish: 'Apocalipsis',
    abbreviation: 'Rev',
    order: 27,
    chapters: 22,
    testament: 'new',
    category: 'apocalypse',
    author: 'John',
    writingDate: '90-110 CE',
  },
];

/**
 * Get book info by ID
 * @param {string} bookId - Book ID (e.g., 'matthew', 'john')
 * @returns {Object} Book info object or null
 */
export function getBook(bookId) {
  return NT_BOOKS.find((b) => b.id === bookId);
}

/**
 * Get book list by category
 * @param {string} category - Category ('gospel', 'epistle', 'history', etc.)
 * @returns {Array} Array of books in category
 */
export function getBooksByCategory(category) {
  return NT_BOOKS.filter((b) => b.category === category);
}

/**
 * Create book reference string
 * @param {string} bookId - Book ID
 * @param {number} chapter - Chapter number
 * @param {number} verse - Verse number (optional)
 * @returns {string} Reference string (e.g., 'John 3:16')
 */
export function createRef(bookId, chapter, verse) {
  const book = getBook(bookId);
  if (!book) return '';
  const ref = `${book.name} ${chapter}`;
  if (verse) return `${ref}:${verse}`;
  return ref;
}

export default {
  NT_BOOKS,
  getBook,
  getBooksByCategory,
  createRef,
};
